---
title: "AngelaNolan_week5_answers"
author: "Angela Nolan"
date: "2024-03-01"
output: html_document
---

1.  What is the probability that a particular allele has at least one copy in the next generation?  The surprising answer quickly becomes independent of population size as *N* becomes larger.  (Hint: Use one minus the probability that the allele has no copies in the next generation and this equation: $\lim\limits_{\varepsilon \to \infty}(1+\varepsilon*x)^\frac{1}{\varepsilon} = e^x$)

-No alleles in the next generation: (1-1\frac{2}N)^2 (for an individual)
- 1-(1-1\frac{2}N)^2N (for a whole generation)
- assuming the population is infinite given e approaching infinity 
1-1\frac{e}=0.632%

2. 
|Year| Individuals|
|------|----------|
| 1950 | 4100 |
| 1951 | 2250 |
| 1952 | 6000 |
| 1953 | 8000 |
| 1954 | 11000 |
| 1955 | 2000 |
| 1956 | 11000 |
| 1957 | 16000 |
| 1958 | 15000 |
| 1959 | 7000 |
| 1960 | 2500 |
| 1961 | 1400 | 
   * Assuming that the actual size of the population in any year equals the effective population size in that year, estimate the average effective number over the entire 12-year period.
   
- Ne=t\frac{sum(1\frac{Ni})}
- Ni= 1\frac{(1/4100)+(1/2250)+(1/6000)+(1/8000)+(1/11000)+(1/2000)+(1/11000)+(1/16000)+(1/15000)+(1/7000)+(1/2500)+(1/1400)}=3936.82

3.  A dairy farmer has a herd consisting of 200 cows and 2 bulls.  What is the effective population size?

- Ne=(4Nm)(Nf)\frac{Nm+Nf}
- 4(2)(200)\frac{2+200}=7.92 or 3.92% of the actual population size 

4. Ne=t\frac{sumNi}
- 5\frac{(1/2)+(1/3)(1/25)+(1/32)+(1/86)} = 5.547

- Average Nc= (2+3+25+32+86)\frac{5} = 29.6

Inbreeding depression is illustrated in this since we have an Ne of 5.547 and need an Ne of at least 50 to avoid the affects of inbreeding depression.

5.
  a. calculate the frequencies of the 2 alleles in each population observed 
    Munich A1: 2(6)+33\frac{120(2)}=0.187.5
    Munich A2: 3(81)+33\frac{120(2)}=0.8125
    
    Innsbruck A1: 2(20)+59\frac{122(2)}=0.4057
    Innsbruck A2: 2(43)+59\frac{122(2)}=0.5492
    
    Verona A1: 2(65)+39\frac{118(2)}=0.7161
    Verona A2: 2(14)+39\frac{118(2)}=0.2838
    
  b. Do any of these populations have excess heterozygotes (calculate genotype frequency=expected)
  
    Munich: (2*0.1875*0.8125)(120)=36.56
    Innsbruck: (2*0.4057*0.5942)(122)=58.8
    Verona: (2*0.7161*0.2838)(118)=47.962
  
    There is an excess of hererozygotes in innsbruck
    There is a defecit of heterozygotes in munich and verona 
  
  c. calculate Fis for each population
    Fis=Hs-Hi\frac{hs} aka exp-obs\frac{exp}
    
    Munich: 36.56-33/36.56=0.0097
    
    Innsbruck: 58.8-59/58.8= -0.0034
    
    Verona: 49.96-39/47.96= -0.1868
  #Fis is positive if there is a defecit and negative if theres an excess of heterozygotes
  
  



