---
title: "Final Project for BIO 594"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## GitHub Documents

This is an R Markdown format used for publishing markdown documents to GitHub. When you click the **Knit** button all R code chunks are run and a markdown file (.md) suitable for publishing to GitHub is generated.

# Link to original github: https://github.com/pdimens/2022-Tatlanticus_popgen

# Data setup
* Population: 12 populations from 5 different localities (10 near sewage effluent sources, 2 controls)
* The sequenced data files are located on KITT and can be accessed via

  PATH:  `/home/BIO594/Final_Project`
* Size: 376 individuals (28-33 per population), 150bp sequences
* Sequences were previously demultiplexed with barcodes and individuals from a different species were removed (completed by Dr. Jon Puritz)

# Bioinformatics

## Initial Raw Data Assessment and Characterization (Jon)
  * Count the RAW reads
  * Examine quality of data (fastqc)

## Reference assembly (Cass)
   * De Novo Reference Assembly 
      * Include optimization
      * Assemble only a subset of individuals

## RADSeq Bioinformatics (Caitlin)
   * Trimming adapters and low quality reads (fastp via dDocent)
   * Read Mapping (BWA & SAMtools via dDocent)
      * Try using different mappaing parameters on a subset and pick the best ones
   * SNP calling and filtering (FreeBayes via dDocent)

## SNP Filtering (VCFtools, vcflib, rad_haplotyper) (Willow)
```{bash, eval=FALSE}
conda create -n Final #create a conda enviro
conda activate Final #activate the conda enviro 
```

### We will apply 3 basic filtering steps 
Remove genotypes with less than 5 reads 
```{bash}
vcftools --vcf TotalRawSNPs.vcf --recode-INFO-all --minDP 5 --out TRSdp5 --recode 
```

```{bash, eval=FALSE}
After filtering, kept 379 out of 379 Individuals
Outputting VCF file...
After filtering, kept 1307614 out of a possible 1307614 Sites
Run Time = 1394.00 seconds
```

Keep variants genotyped in 50% of indv, a min quality score of 30, and minor allele count of 3
```{bash, eval=FALSE}
vcftools --vcf TRSdp5.recode.vcf --recode-INFO-all --max-missing 0.5 --mac 3 --minQ 30 --out TRSdp5g5mac3 --recode
```

```{bash, eval=FALSE}
After filtering, kept 379 out of 379 Individuals
Outputting VCF file...
After filtering, kept 168317 out of a possible 1307614 Sites
Run Time = 275.00 seconds
```

Using Amy's program to filter by minor allele frequency (This isn't in the dDocent instructions and I already filtered by minor allele count so not sure if I should have also run this?)
```{bash, eval=FALSE}
curl -L -O https://raw.githubusercontent.com/jpuritz/dDocent/master/scripts/untested/multi.maf.sh
chmod +x multi.maf.sh
multi.maf.sh TRSdp5g5mac3.recode.vcf 0.001 TRSdp5g5mac3maf
```

```{bash, eval=FALSE}
After filtering, kept 379 out of 379 Individuals
Outputting VCF file...
After filtering, kept 168317 out of a possible 168317 Sites
Run Time = 188.00 seconds
```

Now we will filter out individuals that did not sequence well 
```{bash}
curl -L -O https://raw.githubusercontent.com/jpuritz/dDocent/master/scripts/filter_missing_ind.sh #bash script 
chmod +x filter_missing_ind.sh
./filter_missing_ind.sh TRSdp5g5mac3maf.recode.vcf TRSdp5g5mac3maf5MIa
```

```{bash}
After filtering, kept 379 out of 379 Individuals
Outputting Individual Missingness
After filtering, kept 168317 out of a possible 168317 Sites
Run Time = 14.00 seconds


                                          Histogram of % missing data per individual
     Number of Occurrences
       45 ++---------+----**---+----------+---------+----------+----------+---------+----------+---------+---------++
          +          +    **   +          +         +          'totalmissing' using (bin($1,binwidth)):(1.0) ****** +
          |              ***                                                                                        |
       40 ++             ***                                                                                       ++
          |              ***                                                                                        |
       35 ++             ***                                                                                       ++
          |              ***                                                                                        |
          |              ***                                                                                        |
       30 ++             ***                                                                                       ++
          |              ***                                                                                        |
       25 ++            ****                                                                                       ++
          |             *****                                                                                       |
          |           ********                                                                                      |
       20 ++          ********                                                                                     ++
          |          *********                                                                                      |
       15 ++         *********                                                                                     ++
          |          *********                                                                                      |
          |          *********  **                                                                                  |
       10 ++        ****************                                                                               ++
          |   **    ******************                                                         **                   |
        5 ++  ****  **************** ***                                                     ****                  ++
          |   ********************** *** ******                                              ****               **  |
          + ******* **************** ****** * **********************************************************************+
        0 ++********************************************************************************************************+
          0         0.1       0.2        0.3       0.4        0.5        0.6       0.7        0.8       0.9         1
                                                       % of missing data

The 85% cutoff would be 0.285634
Would you like to set a different cutoff, yes or no
yes
Please enter new cutoff
0.5
All individuals with more than 50.0% missing data will be removed.
Excluding individuals in 'exclude' list
After filtering, kept 341 out of 379 Individuals
Outputting VCF file...
After filtering, kept 168317 out of a possible 168317 Sites
Run Time = 171.00 seconds

```

Removing indv that JP specified as they are a different species. (I should have done this sooner but forgot)
```{bash, eval=FALSE}
vcftools --vcf TRSdp5g5mac3maf5MIa.recode.vcf --remove indv_to_remove.txt --recode-INFO-all --out TRSdp5g5mac3maf5MIasub --recode

```


We will now filter out missing data at the population level 
```{bash}
ln -s ../assembly/popmap . #create a link to the popmap in the assembly file 
curl -L -O https://raw.githubusercontent.com/jpuritz/dDocent/master/scripts/pop_missing_filter.sh
chmod +x pop_missing_filter.sh
./pop_missing_filter.sh TRSdp5g5mac3maf5MIasub.recode.vcf popmap 0.1 1 TRSdp5g5mac3mafMIasubp9
```

```{bash, eval=FALSE}
After filtering, kept 338 out of 338 Individuals
Outputting VCF file...
After filtering, kept 63322 out of a possible 168317 Sites
Run Time = 69.00 seconds
```

Filter out sites with less than 95% overall call rate and minor allele freq of 0.001
```{bash, eval=FALSE}
vcftools --vcf TRSdp5g5mac3mafMIasubp9.recode.vcf --recode-INFO-all --max-missing 0.95 --maf 0.001 --out TRSdp5g5mac3mafMIasubp9g9 --recode

```

```{bash, eval=FALSE}
After filtering, kept 338 out of 338 Individuals
Outputting VCF file...
After filtering, kept 50271 out of a possible 63322 Sites
Run Time = 52.00 seconds
```

Running dDocent filter script - site depth, quality vs depth, strand rep, allelic balance of heterozygotes 
```{bash, eval=FALSE}
curl -L -O https://raw.githubusercontent.com/jpuritz/dDocent/master/scripts/dDocent_filters
chmod +x dDocent_filters
./dDocent_filters TRSdp5g5mac3mafMIasubp9g9.recode.vcf TRSdp5g5mac3mafMIasubp9g9d
```

```{bash, eval=FALSE}
This script will automatically filter a FreeBayes generated VCF file using criteria related to site depth,
quality versus depth, strand representation, allelic balance at heterzygous individuals, and paired read representation.
The script assumes that loci and individuals with low call rates (or depth) have already been removed. 

Contact Jon Puritz (jpuritz@gmail.com) for questions and see script comments for more details on particular filters 

Number of sites filtered based on allele balance at heterozygous loci, locus quality, and mapping quality / Depth
 17176 of 50271 

Are reads expected to overlap?  In other words, is fragment size less than 2X the read length?  Enter yes or no.
yes
Is this from a mixture of SE and PE libraries? Enter yes or no.
no
Number of additional sites filtered based on properly paired status
 960 of 33095 

Number of sites filtered based on high depth and lower than 2*DEPTH quality score
 2536 of 32135 



                                               Histogram of mean depth per site
    Number of Occurrences
      350 +++----+----+----+-----+----+----+----+----+----+-----+-**-+----+----+----+-----+----+----+----+----+----++
          | +    +    +    +     +    +    +    +    +    +'meandepthpersite' using (bin($1,binwidth)):(1.0) ******+|
          |                                                       **                                                |
      300 ++                                      *          *  ****                                               ++
          |                                       *          ** ****    **                                          |
          |                                       *    ***** ** **** *  **                                          |
          |                                       * **************** *  **                                          |
      250 ++                                      ****************** ** ***                                        ++
          |                                     *********************** ***                                         |
          |                                     *********************** *** *                                       |
      200 ++                          *      ** *****************************                                      ++
          |                           *     *********************************                                       |
          |                           *** * *********************************                                       |
      150 ++                       *  *** * *********************************                                      ++
          |                        *  *** * ***********************************                                     |
          |                  ** ** *  *****************************************  **                                 |
      100 ++                ****** ************************************************                                ++
          |                *********************************************************                                |
          |             * **********************************************************                                |
          |             * ************************************************************  *                           |
       50 ++            *************************************************************** **  **                     ++
          |       **** ***************************************************************************   *  *           |
          | +********************************************************************************************************
        0 +++********************************************************************************************************
            16   32   48   64    80   96  112  128  144  160   176  192  208  224  240   256  272  288  304  320  336
                                                          Mean Depth

If distrubtion looks normal, a 1.645 sigma cutoff (~90% of the data) would be 145253.312
The 95% cutoff would be 308
Would you like to use a different maximum mean depth cutoff than 308, yes or no
no
Number of sites filtered based on maximum mean depth
 1685 of 32135 

Number of sites filtered based on within locus depth mismatch
 19 of 30447 

Total number of sites filtered
 19843 of 50271 

Remaining sites
 30428 

Filtered VCF file is called TRSdp5g5mac3mafMIasubp9g9d.FIL.recode.vcf

Filter stats stored in TRSdp5g5mac3mafMIasubp9g9d.filterstats

```

Next we will break up complex mutational events into separate SNP and INDEL (insertion-deletion) calls to remove INDELS
```{bash, eval=FALSE}
vcfallelicprimitives TRSdp5g5mac3mafMIasubp9g9d.FIL.recode.vcf --keep-info --keep-geno > TRSdp5g5mac3mafMIasubp9g9d.prim.vcf
vcftools --vcf TRSdp5g5mac3mafMIasubp9g9d.prim.vcf --remove-indels --recode --recode-INFO-all --out SNP.TRSdp5g5mac3mafMIasubp9g9d

```

```{bash, eval=FALSE}
After filtering, kept 338 out of 338 Individuals
Outputting VCF file...
 Duplicate alternate alleles found at dDocent_Contig_19543:41
 Duplicate alternate alleles found at dDocent_Contig_29303:64
After filtering, kept 26737 out of a possible 28609 Sites
Run Time = 27.00 seconds
```


This data set has technical replicates. JP provided a bash script and tsv file with duplicate sample names. Run the program to produce a list of mismatched loci (i.e. where one replicate has a and another has a g)
```{bash}
bash dup_sample_filter SNP.TRSdp5g5mac3mafMIasubp9g9d.recode.vcf duplicates.samples

```

I got this error when trying to execute the script 
```{bash, eval=FALSE}
Warning: Expected at least 2 parts in FORMAT entry: ID=GL,Number=G,Type=Float,Description="Genotype Likelihood, log10-scaled likelihoods of the data given the called genotype for each possible genotype generated from the reference and alternate alleles given the sample ploidy">
Keeping individuals in 'keep' list
After filtering, kept 1 out of 338 Individuals
Outputting VCF file...
After filtering, kept 26737 out of a possible 26737 Sites
Run Time = 7.00 seconds
rm: cannot remove ‘FBN_327a.recode.vcf’: No such file or directory
rm: cannot remove ‘keep.FBN_327a’: No such file or directory
rm: cannot remove ‘FBN_327b.recode.vcf’: No such file or directory
rm: cannot remove ‘keep.FBN_327b’: No such file or directory
rm: cannot remove ‘FBN_327a.recode.vcf’: No such file or directory
rm: cannot remove ‘FBN_327a.recode.vcf’: No such file or directory
rm: cannot remove ‘keep.FBN_327a’: No such file or directory
rm: cannot remove ‘keep.FBN_327a’: No such file or directory
rm: cannot remove ‘FBN_327c.recode.vcf’: No such file or directory
rm: cannot remove ‘keep.FBN_327c’: No such file or directory
rm: cannot remove ‘FBN_327a.recode.vcf’: No such file or directory
rm: cannot remove ‘FBN_327a.recode.vcf’: No such file or directory
rm: cannot remove ‘keep.FBN_327a’: No such file or directory
rm: cannot remove ‘keep.FBN_327a’: No such file or directory
rm: cannot remove ‘FBN_327d.recode.vcf’: No such file or directory
rm: cannot remove ‘keep.FBN_327d’: No such file or directory
rm: cannot remove ‘FBN_327b.recode.vcf’: No such file or directory
rm: cannot remove ‘FBN_327b.recode.vcf’: No such file or directory
rm: cannot remove ‘keep.FBN_327b’: No such file or directory
rm: cannot remove ‘keep.FBN_327b’: No such file or directory
rm: cannot remove ‘FBN_327c.recode.vcf’: No such file or directory
rm: cannot remove ‘FBN_327c.recode.vcf’: No such file or directory
rm: cannot remove ‘keep.FBN_327c’: No such file or directory
rm: cannot remove ‘keep.FBN_327c’: No such file or directory
rm: cannot remove ‘FBN_327b.recode.vcf’: No such file or directory
rm: cannot remove ‘FBN_327b.recode.vcf’: No such file or directory
rm: cannot remove ‘keep.FBN_327b’: No such file or directory
rm: cannot remove ‘keep.FBN_327b’: No such file or directory
rm: cannot remove ‘FBN_327d.recode.vcf’: No such file or directory
rm: cannot remove ‘FBN_327d.recode.vcf’: No such file or directory
rm: cannot remove ‘keep.FBN_327d’: No such file or directory
rm: cannot remove ‘keep.FBN_327d’: No such file or directory
rm: cannot remove ‘FBN_327c.recode.vcf’: No such file or directory
rm: cannot remove ‘FBN_327c.recode.vcf’: No such file or directory
rm: cannot remove ‘keep.FBN_327c’: No such file or directory
rm: cannot remove ‘keep.FBN_327c’: No such file or directory
rm: cannot remove ‘FBN_327d.recode.vcf’: No such file or directory
rm: cannot remove ‘FBN_327d.recode.vcf’: No such file or directory
rm: cannot remove ‘keep.FBN_327d’: No such file or directory
rm: cannot remove ‘keep.FBN_327d’: No such file or directory
rm: cannot remove ‘OBN_9b.recode.vcf’: No such file or directory
rm: cannot remove ‘keep.OBN_9b’: No such file or directory
rm: cannot remove ‘OBN_9c.recode.vcf’: No such file or directory
rm: cannot remove ‘keep.OBN_9c’: No such file or directory
rm: cannot remove ‘OBN_9b.recode.vcf’: No such file or directory
rm: cannot remove ‘OBN_9b.recode.vcf’: No such file or directory
rm: cannot remove ‘keep.OBN_9b’: No such file or directory
rm: cannot remove ‘keep.OBN_9b’: No such file or directory
rm: cannot remove ‘OBN_9d.recode.vcf’: No such file or directory
rm: cannot remove ‘keep.OBN_9d’: No such file or directory
rm: cannot remove ‘OBN_9c.recode.vcf’: No such file or directory
rm: cannot remove ‘OBN_9c.recode.vcf’: No such file or directory
rm: cannot remove ‘keep.OBN_9c’: No such file or directory
rm: cannot remove ‘keep.OBN_9c’: No such file or directory
rm: cannot remove ‘OBN_9d.recode.vcf’: No such file or directory
rm: cannot remove ‘OBN_9d.recode.vcf’: No such file or directory
rm: cannot remove ‘keep.OBN_9d’: No such file or directory
rm: cannot remove ‘keep.OBN_9d’: No such file or directory
rm: cannot remove ‘OBS_245a.recode.vcf’: No such file or directory
rm: cannot remove ‘keep.OBS_245a’: No such file or directory
rm: cannot remove ‘OBS_245b.recode.vcf’: No such file or directory
rm: cannot remove ‘keep.OBS_245b’: No such file or directory
rm: cannot remove ‘OBS_245a.recode.vcf’: No such file or directory
rm: cannot remove ‘OBS_245a.recode.vcf’: No such file or directory
rm: cannot remove ‘keep.OBS_245a’: No such file or directory
rm: cannot remove ‘keep.OBS_245a’: No such file or directory
rm: cannot remove ‘OBS_245c.recode.vcf’: No such file or directory
rm: cannot remove ‘keep.OBS_245c’: No such file or directory
rm: cannot remove ‘OBS_245a.recode.vcf’: No such file or directory
rm: cannot remove ‘OBS_245a.recode.vcf’: No such file or directory
rm: cannot remove ‘keep.OBS_245a’: No such file or directory
rm: cannot remove ‘keep.OBS_245a’: No such file or directory
rm: cannot remove ‘OBS_245d.recode.vcf’: No such file or directory
rm: cannot remove ‘keep.OBS_245d’: No such file or directory
rm: cannot remove ‘OBS_245b.recode.vcf’: No such file or directory
rm: cannot remove ‘OBS_245b.recode.vcf’: No such file or directory
rm: cannot remove ‘keep.OBS_245b’: No such file or directory
rm: cannot remove ‘keep.OBS_245b’: No such file or directory
rm: cannot remove ‘OBS_245c.recode.vcf’: No such file or directory
rm: cannot remove ‘OBS_245c.recode.vcf’: No such file or directory
rm: cannot remove ‘keep.OBS_245c’: No such file or directory
rm: cannot remove ‘keep.OBS_245c’: No such file or directory
rm: cannot remove ‘OBS_245b.recode.vcf’: No such file or directory
rm: cannot remove ‘OBS_245b.recode.vcf’: No such file or directory
rm: cannot remove ‘keep.OBS_245b’: No such file or directory
rm: cannot remove ‘keep.OBS_245b’: No such file or directory
rm: cannot remove ‘OBS_245d.recode.vcf’: No such file or directory
rm: cannot remove ‘OBS_245d.recode.vcf’: No such file or directory
rm: cannot remove ‘keep.OBS_245d’: No such file or directory
rm: cannot remove ‘keep.OBS_245d’: No such file or directory
rm: cannot remove ‘OBS_245c.recode.vcf’: No such file or directory
rm: cannot remove ‘OBS_245c.recode.vcf’: No such file or directory
rm: cannot remove ‘keep.OBS_245c’: No such file or directory
rm: cannot remove ‘keep.OBS_245c’: No such file or directory
rm: cannot remove ‘OBS_245d.recode.vcf’: No such file or directory
rm: cannot remove ‘OBS_245d.recode.vcf’: No such file or directory
rm: cannot remove ‘keep.OBS_245d’: No such file or directory
rm: cannot remove ‘keep.OBS_245d’: No such file or directory
```


# Population-level Analyses

## Detecting Selection Via Outlier Detection Programs (Flow and Michelle)
      * RDA 
      * Bayenv2
      * PCAadapt
      * Outflank

## Detecting Population Structure (Brittany and Angela)
      * Pairwise *F~ST~*
      * Genetic diversity (observed and expected heterozygosity)
      * EEMS (https://www.nature.com/articles/ng.3464)

